#!/bin/bash
cp implementation/system.bit ../bit_files/window_and_fft_test_v4_2019_Aug_16_1218.bit
./mkbof_64 -o implementation/system.bof -s core_info.tab -t 3 implementation/system.bin
cp implementation/system.bof ../bit_files/window_and_fft_test_v4_2019_Aug_16_1218.bof
cp design_info.tab ../bit_files/window_and_fft_test_v4_2019_Aug_16_1218.info
gzip -c ../bit_files/window_and_fft_test_v4_2019_Aug_16_1218.bof  > ../bit_files/window_and_fft_test_v4_2019_Aug_16_1218.bof.gz
gzip -c implementation/system.bin > implementation/system.bin.gz
cat implementation/system.bin.gz >> /home/heystek/heystek_thesis/thesis/window_and_fft_test_v4/XPS_ROACH2_base/extended_info.kcpfpg
cp extended_info.kcpfpg ../bit_files/window_and_fft_test_v4_2019_Aug_16_1218.fpg
