#!/bin/bash
cp implementation/system.bit ../bit_files/window_design_2019_Feb_06_1543.bit
./mkbof_64 -o implementation/system.bof -s core_info.tab -t 3 implementation/system.bin
cp implementation/system.bof ../bit_files/window_design_2019_Feb_06_1543.bof
cp design_info.tab ../bit_files/window_design_2019_Feb_06_1543.info
gzip -c ../bit_files/window_design_2019_Feb_06_1543.bof  > ../bit_files/window_design_2019_Feb_06_1543.bof.gz
gzip -c implementation/system.bin > implementation/system.bin.gz
cat implementation/system.bin.gz >> /home/heystek/heystek_thesis/thesis/window_design/XPS_ROACH2_base/extended_info.kcpfpg
cp extended_info.kcpfpg ../bit_files/window_design_2019_Feb_06_1543.fpg
